import { decodeR } from "./src";

const r = decodeR("eyJwYXJhbXMiOnsiZ2FtZUlkIjoieTY1Nzk3ZGUiLCJjYXRlZ29yeUlkIjoibjJ5MzUwZWQiLCJ2ZXJpZmllZCI6MSwib2Jzb2xldGUiOjEsInZhbHVlcyI6W3sidmFyaWFibGVJZCI6Imo4NGVlZzJuIiwidmFsdWVJZHMiOlsiMjFneTZwODEiXX0seyJ2YXJpYWJsZUlkIjoib252NDdvbW4iLCJ2YWx1ZUlkcyI6WyJwMTI3ajM0cSJdfV19LCJwYWdlIjoxOTN9")
console.log(JSON.stringify(r, undefined, 2))
